name: docker-test
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Docker image url'
        required: true
        default: ''
        type: string

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: ${{ inputs.repository }}
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull-image
        run: docker pull "${{ env.IMAGE_NAME }}"
      - name: check images
        run: docker image ls
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
      

