name: First workflow

on:
  push:
    branches:
      - main

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubuntu
        run: cat /etc/os-release
      - name: Exibir mensagem
        run: echo "Test workflow" > mensagem.txt
      - name: Lista arquivos
        run: ls -lha 
      - name: mostra arquivo mensagem
        run: cat mensagem.txt
