name: trabalho_entre_jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubuntu
        run: cat /etc/os-release

      - name: Exibir mensagem
        run: echo "Test workflow" > ${{ github.workspace }}/mensagem.txt

      - name: Lista arquivos
        run: ls -lha 

      - name: mostra arquivo mensagem
        run: cat mensagem.txt

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-upload 
          path: ${{ github.workspace }}/mensagem.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubuntu
        run: cat /etc/os-release

      - uses: actions/download-artifact@v4
        with:
          name: artifacts-upload
          path: artifacts

      - name: Lista arquivos
        run: ls -lha 

      - name: ver conteudo diretorio
        run: ls -lha && ls ./artifacts

      - name: Acessa arquivo 
        run: mv artifacts/mensagem.txt . && rm -rf ./artifacts    

      - name: Ver o conteudo do diretório novamente
        run: ls -lha

      - name: mostra arquivo mensagem
        run: cat mensagem.txt
